name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
branches:
  - master
  - develop
categories:
  - title: 🚀 Features
    label: enhancement
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore
template: |
  ## Changes

  $CHANGES