_extends: plumbing

# These settings are synced to GitHub by https://probot.github.io/apps/settings/
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: gh-playgound

  # A short description of the repository that will show up on GitHub
  description: description of repo

  # A URL with more information about the repository
  homepage: https://nolte.github.io/gh-playgound

  # A comma-separated list of topics to set on the repository
  topics: github, probot
