name: cicd

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: dummy action
        run: |
          echo "hallo"